/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.example

class App {
    val greeting: String
        get() {
            return "Hello World! Test #2."
        }
}

fun main() {
    println(App().greeting)
}
